### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by softgrass** [Da532/Da-website-Legacy#2]
How do I use a website I tried using wix but it dosent work

**Comment by foxt** [comment]
you click the 
![020202-1](https://user-images.githubusercontent.com/12257112/29951804-1c5bc128-8ebd-11e7-8142-c203262505e2.png)
button
then click the
![020202-1](https://user-images.githubusercontent.com/12257112/29951804-1c5bc128-8ebd-11e7-8142-c203262505e2.png)
button then click
![020202-1](https://user-images.githubusercontent.com/12257112/29951804-1c5bc128-8ebd-11e7-8142-c203262505e2.png)
and you should be done
